// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYvtOcxJHui0sS8bkxRTWa1pfcb5MBges',
    appId: '1:337707428578:web:f938f5fdcca6faad3a0cbb',
    messagingSenderId: '337707428578',
    projectId: 'test-7342b',
    authDomain: 'test-7342b.firebaseapp.com',
    storageBucket: 'test-7342b.appspot.com',
    measurementId: 'G-QTP2PGP424',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy8Lwjyn3hApZO0uy2q_kn5GMVn6voss0',
    appId: '1:337707428578:android:5616d99ea51d996f3a0cbb',
    messagingSenderId: '337707428578',
    projectId: 'test-7342b',
    storageBucket: 'test-7342b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhmyS8qczz1R-jXfRjntXOikL-CSLV9gU',
    appId: '1:337707428578:ios:f432ede6e0b7fc103a0cbb',
    messagingSenderId: '337707428578',
    projectId: 'test-7342b',
    storageBucket: 'test-7342b.appspot.com',
    androidClientId: '337707428578-0lbs93o0f43tf4kmrp9ctrj7a9s9tafc.apps.googleusercontent.com',
    iosClientId: '337707428578-ai540p5lbhdi8vu9nhm7vomk1um43mvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.partier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhmyS8qczz1R-jXfRjntXOikL-CSLV9gU',
    appId: '1:337707428578:ios:f432ede6e0b7fc103a0cbb',
    messagingSenderId: '337707428578',
    projectId: 'test-7342b',
    storageBucket: 'test-7342b.appspot.com',
    androidClientId: '337707428578-0lbs93o0f43tf4kmrp9ctrj7a9s9tafc.apps.googleusercontent.com',
    iosClientId: '337707428578-ai540p5lbhdi8vu9nhm7vomk1um43mvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.partier',
  );
}
